apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-backend
  labels:
    app: tutorial-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutorial-backend
  template:
    metadata:
      labels:
        app: tutorial-backend
    spec:
      containers:
      - name: backend
        image: ${REGISTRY_URL}/tutorial-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tutorial-secrets
              key: openai-api-key
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: tutorial-secrets
              key: github-token
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
        volumeMounts:
        - name: tutorial-output
          mountPath: /app/output
        - name: logs-volume
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /jobs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /jobs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: tutorial-output
        persistentVolumeClaim:
          claimName: tutorial-output-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-frontend
  labels:
    app: tutorial-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutorial-frontend
  template:
    metadata:
      labels:
        app: tutorial-frontend
    spec:
      containers:
      - name: frontend
        image: ${REGISTRY_URL}/tutorial-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://tutorial-backend-service:8000"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-backend-service
spec:
  selector:
    app: tutorial-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-frontend-service
spec:
  selector:
    app: tutorial-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-output-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard 